name: Release new action version
on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
defaults:
  run:
    shell: pwsh

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    # Remember to configure the releaseNewActionVersion environment with required approvers in the repository settings
    environment:
      name: releaseNewActionVersion
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: step-security/harden-runner@v1
      with:
        allowed-endpoints: 
          api.github.com:443
          github.com:443

    - uses: actions/checkout@v2
    - name: Update the rc tag
      uses: step-security/publish-action@63abd0d521e21329399edb30e8f577a7ab85443c
      with:
        source-tag: ${{ env.TAG_NAME }}
        rc: true

    - name: Canary test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
        canary: true

    - name: Update the ${{ env.TAG_NAME }} tag
      uses: step-security/publish-action@63abd0d521e21329399edb30e8f577a7ab85443c
      with:
        source-tag: ${{ env.TAG_NAME }}
